# -*- coding: utf-8 -*-
"""convert_grib2_to_parquet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16dpdR6VmRmHReJbu8SngrMKA4CYG-9aL
"""

# Use these pip commands in a notebook
# !pip install cfgrib
# !pip install eccodes
# !pip install ecmwflibs

import cfgrib
import pandas as pd
import xarray as xr

ds = xr.open_dataset(
    "/home/arome__001__SP1__00H__2024-04-09T06_00_00Z.grib2",
    engine="cfgrib",
    filter_by_keys={'typeOfLevel': 'heightAboveGround', 'level': 2}
)
ds

df = ds.to_dataframe()
df

df.to_parquet("/home/arome__001__SP1__00H__2024-04-09T06_00_00Z_heightAboveGround_2.parquet")